### ISSUE TITLE
How to use Dice loss for multiple class segmentation?

### ISSUE THREAD

**Issue by John1231983** [HolmesShuan/Dice-coefficient-Loss-Caffe-Layer#1]
Thanks for your works. 
I am working in brain segmentation that segment brain into 4 classes: CSF, WM, GM and background. Currently, I am using softmax layer that can work for 4 classes. However, I want to use your dice loss layer.  Do you have any idea to use your dice loss layer for 4 classes? Thanks

**Comment by HolmesShuan** [comment]
You may see my implementation of Dice Loss as a kind of Euclidean Loss with weaker supervision. I guess what u want is more like [**Unet structure**](https://github.com/yihui-he/u-net) with generalized dice loss. Here is the [Link](https://github.com/yihui-he/caffe-dice-loss-layer);

**Comment by John1231983** [comment]
Thanks. I read it before but it is not suitable for my case. I found another solution likes 
1. Convert it to a hard decision by using softmax layer
2. Then apply your Dice layer with bottoms are softmax and ground-truth (label). 

However, I got an error about dimension. I guess it because your dice layer only support 4D input, while my input is 5D (such as 3D-Unet : `sample x channel x depth x height x weight`) . Do you know how to fix it? Note that, I am using `batch_size: 4`, so I think the 1048576 is for the whole batch_size, while `262144` is only for 1 batch of label. Thanks

`dice_coef_loss_layer.cpp:12] Check failed: bottom[0]->count(1) == bottom[1]->count(1) (1048576 vs. 262144) Inputs must have the same dimension.`

This is my prototxt

```
layer {
    name: "softmax"
    type: "Softmax"
    bottom: "deconv"
    top: "softmax_hard"
}


layer {
  name: "loss"
  type: "DiceCoefLoss"
  bottom: "softmax_hard"
  bottom: "label"
  top: "loss"
}
```

**Comment by HolmesShuan** [comment]
If you want to use 5D input, that is OK. After softmax, former shape is not important. It seems that your label dim did not equal to softmax output. If your `batchsize=4`, why `label_size=1` ?

**Comment by John1231983** [comment]
I just guess it. The error is from your code. 

I used softmaxwithloss and it worked for `batch_size=4`. However, it was fail with your layer. Hence, I just guess the reason. 

Sorry it is not from batch_size. It from number of output in deconv. I have 4 classes in deconvolution. Hence, num_output is 4

**Comment by HolmesShuan** [comment]
`bottom[0]->count(1) == bottom[1]->count(1)` means the dim of `channel x height x weight` in 4D or `channel x depth x height x weight` in 5D. Which means in each batch, the dim to calculate loss is unequal.
U may change dice loss to Euclidean loss to quick check your structure.

**Comment by John1231983** [comment]
I am testing in 5D. I tested with softmaxwithloss and it worked. However, your layer did not work

**Comment by HolmesShuan** [comment]
As I said before, dice loss is more like Euclidean loss rather than Softmax loss which used in regression problem. Euclidean Loss layer is standard Caffe layer, just exchange dice loss to Euclidean loss won't affect Ur performance. Just for a test.

**Comment by John1231983** [comment]
Finally, I found the reason. The softmax gives the soft result(range in [0,1]). Hence, we need an extra step in the dice loss layer to convert it to hard result (value in {0,1}). I checked it in your code and I did not find any line to do it. Hence, I think for segmentation task, it is better include it in the code as VNet do https://github.com/faustomilletari/VNet/blob/master/pyLayer.py

**Comment by HolmesShuan** [comment]
All right... Please notice my `readme.md` , my formula is `(2xy+s)/(sum(x.^2)+sum(y.^2)+s)`. Ur wish is `(2xy+s)/(sum(x)+sum(y)+s)`. In my code, both x and y are float32 rather than {0,1}. Thanks to Ur advice, I will change my `readme.md` to further explain the diff.

**Comment by John1231983** [comment]
Could you give me some advice for work ? In my case, my output is a softmax output. For example, the softmax output is 1x4x64x64x64, where 4 is number of class, while the label is 1x1x64x64x64

**Comment by HolmesShuan** [comment]
4 classes: CSF, WM, GM and background, you mean? Label is 0,1,2 and 3 or something like that?

**Comment by John1231983** [comment]
Right. And output of prediction is 1x4x64x64x64, each position is a float32

**Comment by HolmesShuan** [comment]
Binarize.
