### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by debinz** [HolmesShuan/Dice-coefficient-Loss-Caffe-Layer#4]
I have added the cpp, cu and  hpp file into the src/caffe/layers/, and also added the "DICE_DICE_LOSS" at caffe.proto line ~1200. When I started to rebuild the 3D-caffe, it occurred an error: 

PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/layers/dice_coef_loss_layer.cpp
caffe.proto:1273:26: Expected enum constant name.
Makefile:629: recipe for target '.build_release/src/caffe/proto/caffe.pb.cc' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 1
make: *** Waiting for unfinished jobs....

Can you tell me how to solved it? Thanks a lot!!!

**Comment by HolmesShuan** [comment]
Sorry about that. `No need` to change the Caffe.proto anymore. Also, this unofficial layer has `never` been tested on 3D-Caffe, yet.
