### ISSUE TITLE
What dose the layer compute？

### ISSUE THREAD

**Issue by debinz** [HolmesShuan/Dice-coefficient-Loss-Caffe-Layer#5]
When i use the layer to train my model, the loss did not going down, remaining 1.2**, Can you tell me what the layer compute？ dice coefficient or 1- dice coefficient? 

Thanks a lot!

**Comment by HolmesShuan** [comment]
**_Sorry_** for the former misleading introduction. We have updated `README`, hopefully, you may find the answer.
